name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE_REPO: ghcr.io/ndsl6211/char-avatar-generator

jobs:
  metadata:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.tag.outputs.IMAGE_TAG }}
    steps:
      - name: Set image tag
        id: tag
        run: echo "IMAGE_TAG=${GITHUB_SHA::8}" >> $GITHUB_OUTPUT

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

  build-docker-image:
    runs-on: ubuntu-latest
    needs:
      - build
      - metadata
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: docker/Dockerfile
          tags: ${{ env.DOCKER_IMAGE_REPO }}:${{ needs.metadata.outputs.IMAGE_TAG }}

  update-manifest:
    runs-on: ubuntu-latest
    needs:
      - metadata
      - build-docker-image
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup git
        run: |
          git config --global user.name "mashu-deploy-bot"
          git config --global user.email "ndsl6211@gmail.com"

      - name: Checkout Manifest Repo
        uses: actions/checkout@v4
        with:
          repository: ndsl6211/kube-manifests
          token: ${{ secrets.PAT }}
          path: kube-manifests

      - name: Setup kustomize
        uses: imranismail/setup-kustomize@v2

      - name: Update image tag
        run: |
          cd kube-manifests/apps
          kustomize edit set image ${{ env.DOCKER_IMAGE_REPO }}=${{ env.DOCKER_IMAGE_REPO }}:${{ needs.metadata.outputs.IMAGE_TAG }}

      - name: Commit and Push Changes
        run: |
          cd kube-manifests
          git add apps/kustomization.yaml
          git commit -m "Update image tag to ${{ github.sha }}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
